export { SparklesBackground, DotsBackground, GridsBackground } from './backgrounds';
export { Breadcrumbs } from './breadcrumbs';
export { BreadcrumbsRow } from './breadcrumbs-row';
export { BetaBadge } from './beta-badge';
export { BetaBanner } from './beta-banner';
export { Logo } from './logo';
export { ProtectedRoute } from './protected-route';
export { PublicRoute } from './public-route';
export { QuickSettings } from './quick-settings';
export { UserMenu, UserMenuAbsolute } from './user-menu';
export { ApiErrorAlert } from './api-error-alert';
export { FeatureCard } from './feature-card';
export { AuthLayout, AuthHeader } from './auth-layout';
export { AuthInputField } from './auth-input-field';
export { ErrorShell } from './error-shell';
export { ModuleErrorBoundary } from './module-error-boundary';
export { CommandPalette } from './command-palette';
export { GlobalSidebar, GlobalSidebarContent } from './global-sidebar';
export { TabBar } from './tab-bar';
export { AppShell } from './app-shell';
export { TabManager } from './tab-manager';
export { MobileBottomBar } from './mobile-bottom-bar';
export { ResumeWorkspaceButton } from './resume-workspace-button';
export { AppTopBar } from './app-top-bar';
export { FocusModeIndicator } from './focus-mode-indicator';
export { ModuleToolbar } from './module-toolbar';
export { ActivityBar } from './activity-bar';
export { StatusBar } from './status-bar';
export { MenuBar } from './menu-bar';
export { PlatformMegaMenu } from './platform-mega-menu';
export { BottomPanel, BottomPanelContent } from './bottom-panel';
export { TabContextMenu } from './tab-context-menu';
export { BarContextMenu, MenuItem, MenuSeparator, SubMenu, useBarContextMenuState } from './bar-context-menu';
export { SecondarySidebar, SecondarySidebarContent } from './secondary-sidebar';
export { SidebarStack, StackLayoutToggle, useSidebarStackContext, type StackPanelMeta, type SidebarStackContextValue } from './sidebar-stack';
export { SplitEditorPane } from './split-editor-pane';
export { EditorGroupProvider, useEditorGroupId } from './editor-group-context';
export { SidebarPortalZone, SplitPortalPanel } from './sidebar-portal-zone';
export { UnifiedSidebarContent, useUnifiedSidebarContext, registerPanelRenderer, getPanelRenderer } from './unified-sidebar';
export { useRegisterAppPanels, useRegisterDetailPanel, usePanelRenderer, getPanelTitleKey } from './app-panel-bridge';
export { WhatsNewModal } from './whats-new-modal';
