export { useAuthStore, getAvatarUrl, type User } from './auth-store';
export { useThemeStore, type Density } from './theme-store';
export { useLanguageStore, LANGUAGES } from './language-store';
export { useSidebarStore } from './sidebar-store';
export { useViewStore } from './view-store';
export { useWorkspaceStore, type RecentModule, type ModuleContext } from './workspace-store';
export type { WorkspaceSnapshot } from '@/lib/workspace-snapshot';
export { useTabsStore, TAB_GROUP_COLORS, type Tab, type TabGroup, type TabGroupColorId } from './tabs-store';
export { useCommandPaletteStore, type PaletteMode } from './command-palette-store';
export { useActivityBarStore, type ActivityBarItemId, type ActivityBarItem, type ActivityBarPosition } from './activity-bar-store';
export { useKeybindingsStore, formatKeyCombo, type KeybindingActionId, type KeyCombo, type KeybindingEntry } from './keybindings-store';
export { useDashboardStore, DEFAULT_SHORTCUTS, type WidgetId, type WidgetConfig, type ShortcutConfig } from './dashboard-store';
export { useProfilesStore, PROFILE_ICONS, captureSnapshot, applySnapshot, type WorkspaceProfile, type ProfileSnapshot, type ProfileIconId } from './profiles-store';
export { useStatusBarStore, type StatusBarItem, type StatusBarItemPosition } from './status-bar-store';
export { useModuleFiltersStore, DEFAULT_GROUP_ID as FILTERS_DEFAULT_GROUP, SPLIT_GROUP_ID as FILTERS_SPLIT_GROUP, type ModuleFiltersRegistration } from './module-filters-store';
export { useModuleDetailStore, DEFAULT_GROUP_ID as DETAIL_DEFAULT_GROUP, SPLIT_GROUP_ID as DETAIL_SPLIT_GROUP, type ModuleDetailRegistration } from './module-detail-store';
export { useModuleToolbarStore, type ModuleToolbarRegistration } from './module-toolbar-store';
export { useEditorGroupsStore, type EditorGroup, type SplitDirection } from './editor-groups-store';
export { useBottomPanelStore, type BottomPanelTab, type BuiltinTab, type ActivityLogEntry, type DynamicBottomTab, type BottomPanelAlignment } from './bottom-panel-store';
export { useSidebarStackStore, type SidebarSide, type StackLayout, type StackedPanel } from './sidebar-stack-store';
export { useLayoutStore } from './layout-store';
export { useSidebarModeStore, type SidebarMode } from './sidebar-mode-store';
export { usePanelRegistryStore, type PanelZone, type PanelCategory, type SidebarViewMode, type PanelRegistration, type SidebarZoneState } from './panel-registry-store';
export { useHistoryStore } from './history-store';
export { useTourStore } from './tour-store';
