import { logger } from './logger';
import {
    Activity,
    ArrowUpDown,
    BarChart3,
    Bell,
    BookOpen,
    Brain,
    Bug,
    Building2,
    Calendar, CalendarCheck,
    CheckSquare,
    Clock,
    Coffee,
    ContactRound,
    Database,
    Dna,
    FileText,
    Filter,
    FlaskConical,
    Headset,
    Heart,
    HelpCircle,
    History,
    Home,
    ScrollText,
    Keyboard,
    Languages,
    LayoutDashboard,
    LayoutGrid,
    LifeBuoy,
    LucideIcon,
    Mail,
    Maximize,
    MessageCircle,
    Microscope,
    Minimize2,
    Monitor,
    Moon,
    NotebookPen,
    Package,
    PanelLeft,
    PanelRight,
    PanelTop,
    Pill,
    Presentation,
    Settings,
    Share2,
    Shield,
    ShieldCheck,
    SlidersHorizontal,
    Sparkles,
    Sprout,
    StickyNote,
    Sun,
    Syringe,
    TestTube,
    User,
    Users,
    Zap,
    Plus,
    Download,
    GitCompareArrows,
    LayoutList,
    Library,
} from 'lucide-react';

export const MODULE_ICONS_MAP: Record<string, LucideIcon> = {
    'bug': Bug,
    'building-2': Building2,
    'leaf': Sprout,
    'dna': Dna,
    'shield': Shield,
    'shield-check': ShieldCheck,
    'flask-conical': FlaskConical,
    'message-circle': MessageCircle,
    'headset': Headset,
    'mail': Mail,
    'calendar': Calendar,
    'calendar-check': CalendarCheck,
    'package': Package,
    'microscope': Microscope,
    'heart': Heart,
    'brain': Brain,
    'syringe': Syringe,
    'test-tube': TestTube,
    'pill': Pill,
    'activity': Activity,
    'book-open': BookOpen,
    'home': Home,
    'notebook-pen': NotebookPen,
    'share-2': Share2,
    'life-buoy': LifeBuoy,
    'bell': Bell,
    'contact-round': ContactRound,
    'user': User,
    'users': Users,
    'sticky-note': StickyNote,
    'file': FileText,
    'settings': Settings,
    // Status bar icons
    'database': Database,
    'filter': Filter,
    'sliders-horizontal': SlidersHorizontal,
    'check-square': CheckSquare,
    'arrow-up-down': ArrowUpDown,
    // Action icons (used by recent action items)
    'sun': Sun,
    'moon': Moon,
    'languages': Languages,
    'panel-top': PanelTop,
    'panel-left': PanelLeft,
    'panel-right': PanelRight,
    'scroll-text': ScrollText,
    'layout-grid': LayoutGrid,
    'maximize': Maximize,
    'minimize-2': Minimize2,
    'keyboard': Keyboard,
    'layout-dashboard': LayoutDashboard,
    'bar-chart-3': BarChart3,
    'zap': Zap,
    'clock': Clock,
    'history': History,
    // Toolbar action icons
    'plus': Plus,
    'download': Download,
    'git-compare-arrows': GitCompareArrows,
    'layout-list': LayoutList,
    // Profile icons
    'coffee': Coffee,
    'monitor': Monitor,
    'presentation': Presentation,
    'sparkles': Sparkles,
    'help-circle': HelpCircle,
    'library-big': Library,
};

export function getModuleIcon(name: string): LucideIcon {
    const icon = MODULE_ICONS_MAP[name];
    if (!icon && import.meta.env.DEV) {
        logger.warn(`Unknown icon: "${name}" — using fallback`);
    }
    return icon || HelpCircle;
}
